In [1]:
import pandas as pd

In [15]:
with open("ola.pre", "r") as fname:
    v = []
    g_ref  = []
    fname.seek(249)
    contents = fname.readlines()
    #print(contents[0:10])
    for line in contents: # loops through the contents of the file and returns the Grid-ref and values
        if line.startswith("Grid-ref="): # this removes the string and allows access to the x and y refs
            nline = line.strip('Grid-ref=') # strips and makes lists line by line
            nline = nline.rstrip()
            nline = nline.lstrip()
            nline = nline.split(',') 
            nline =  [nline]*12
            
            for grid in nline:
                gref = g_ref.append(grid)
    #print(g_ref)
    pd_ref = pd.DataFrame(g_ref, columns=['Xref', 'Yref'])

In [16]:
pd_ref.head(20)

   Xref  Yref
0     1   148
1     1   148
2     1   148
3     1   148
4     1   148
5     1   148
6     1   148
7     1   148
8     1   148
9     1   148
10    1   148
11    1   148
12    1   311
13    1   311
14    1   311
15    1   311
16    1   311
17    1   311
18    1   311
19    1   311